# Generated by Django 3.2.16 on 2023-10-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
