# Generated by Django 3.2.16 on 2023-11-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_comment_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
